version: '3.7'
services:

  idp:
    build: 
      context: ./
      dockerfile: cmd/idp/Dockerfile
    restart: unless-stopped
    container_name: lifelink-idp
    ports:
    - "10876:10876"
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j 

  gateway:
    build: 
      context: ./
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    container_name: lifelink-gateway
    ports:
    - "8080:8080"
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j 

  users-api:
    build: 
      context: ./
      dockerfile: cmd/users/Dockerfile
    restart: unless-stopped
    container_name: lifelink-users-api
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j 
      ADMIN_API_HOST: lifelink-gateway
      USERS_API_HOST: lifelink-users-api

networks:
  lifelink:
    name: lifelink