version: '3.7'
services:

  idp:
    build:
      context: ./
      dockerfile: cmd/idp/Dockerfile
    restart: unless-stopped
    container_name: lifelink-idp
    ports:
    - "10867:10867"
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j
      ADMIN_API_HOST: lifelink-gateway
      USERS_API_HOST: lifelink-users-api

  gateway:
    build:
      context: ./
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    container_name: lifelink-gateway
    ports:
    - "8081:8080"
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j

  users-api:
    build:
      context: ./
      dockerfile: cmd/users/Dockerfile
    restart: unless-stopped
    container_name: lifelink-users-api
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j

  habits-api:
    build:
      context: ./
      dockerfile: cmd/habits/Dockerfile
    restart: unless-stopped
    container_name: lifelink-habits-api
    networks:
    - lifelink
    environment:
      NEO4J_HOST: neo4j

networks:
  lifelink:
    name: lifelink