version: '3.7'
services:

  idp:
    build:
      context: ./
      dockerfile: cmd/idp/Dockerfile
    restart: unless-stopped
    container_name: lifelink-idp
    networks:
    - lifelink
    - core
    env_file:
    - cmd/idp/.env

  gateway:
    build:
      context: ./
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    container_name: lifelink-gateway
    networks:
    - lifelink
    - core
    env_file:
    - cmd/gateway/.env

  users-api:
    build:
      context: ./
      dockerfile: cmd/users/Dockerfile
    restart: unless-stopped
    container_name: lifelink-users-api
    networks:
    - lifelink
    env_file:
    - cmd/users/.env

  habits-api:
    build:
      context: ./
      dockerfile: cmd/habits/Dockerfile
    restart: unless-stopped
    container_name: lifelink-habits-api
    networks:
    - lifelink
    env_file:
    - cmd/habits/.env

  ui:
    build:
      context: ./ui
      dockerfile: ui/Dockerfile
    restart: unless-stopped
    container_name: lifelink-ui
    networks:
    - lifelink
    - core

networks:
  lifelink:
    name: lifelink
  core:
    name: core